# -*- coding: utf-8 -*-
"""ai_text_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QYA5Qo10Elcnid9L8m5LehhlOfPwsT-p
"""

!pip install gradio transformers torch

import gradio as gr
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"

tokenizer = AutoTokenizer.from_pretrained("gpt2")

model = AutoModelForCausalLM.from_pretrained(
    "gpt2",
    pad_token_id=tokenizer.eos_token_id
).to(device)

def generate_text(prompt):
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    output = model.generate(
        **inputs,
        max_new_tokens=60,
        do_sample=True,
        top_k=50,
        top_p=0.95,
        temperature=0.7
    )

    return tokenizer.decode(output[0], skip_special_tokens=True)

with gr.Blocks() as demo:
    gr.Markdown("# 🤖 AI Text Generator")

    prompt = gr.Textbox(label="Enter Prompt", placeholder="e.g. Artificial Intelligence is")

    output = gr.Textbox(label="Generated Output",lines=5)

    with gr.Row():
        submit_btn = gr.Button("Generate")
        clear_btn = gr.Button("Clear")

    submit_btn.click(generate_text, inputs=prompt, outputs=output)
    clear_btn.click(lambda: ("",""), outputs=[prompt, output])

demo.launch()